ALL: partA partB1 partB2 partB3 partC1 partC2 partC3

partA:partA.c
	gcc -g partA.c -o partA -lrt
	
partB1:partB1.c
	gcc -g partB1.c -o partB1 -lrt

partB2:partB2.c
	gcc -g partB2.c -o partB2 -lrt
	
partB3:partB3.c
	gcc -g partB3.c -o partB3 -lrt


partC1:partC1.c
	gcc -g partC1.c -o partC1 -lrt

partC2:partC2.c
	gcc -g partC2.c -o partC2 -lrt
	
partC3:partC3.c
	gcc -g partC3.c -o partC3 -lrt


##RUN with ./partX CHILDREN 99999999999999999
