ALL: create_shm read_shm delete_shm

create_shm:create_shm.c
	gcc -g create_shm.c -o create_shm

read_shm:read_shm.c
	gcc -g read_shm.c -o read_shm

delete_shm:delete_shm.c
	gcc -g delete_shm.c -o delete_shm
