# Joseph Schechter lab5 makefile
all: lab5 lab5a lab5b

lab5: lab5.o
	gcc -g -Wall lab5.o -o lab5

lab5.o: lab5.s
	gcc -g -Wall -c lab5.s -o lab5.o


lab5a: lab5a.o
	gcc -g -Wall lab5a.o -o lab5a

lab5a.o: lab5a.s
	gcc -g -Wall -c lab5a.s -o lab5a.o


lab5b: lab5b.o
	gcc -g -Wall lab5b.o -o lab5b

lab5b.o: lab5b.s
	gcc -g -Wall -c lab5b.s -o lab5b.o
